version: 0.2

phases:
  pre_build:
    commands:
      - cd server
      - echo Logging in to Amazon ECR...
      - export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_NAME="url-shortener-repo"
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed successfully.
      - echo Tagging the image...
      - docker tag $REPOSITORY_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG
      - echo Pushing the image to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
